# Dicionário de textos multilíngue da plataforma
TEXTOS = {
    'pt': {
        'painel_geral': 'Painel Geral',
        'cursos': 'Cursos',
        'sessoes': 'Sessões',
        'acompanhamento': 'Acompanhamento',
        'cadastros': 'Cadastros',
        'sair': 'Sair / Logout',
        'conectado': 'Conectado como',
        'tema': 'Tema',
        'idioma': 'Idioma',
        'btn_cursos': 'Cursos',
        'btn_acompanhamento': 'Meu Acompanhamento',
        'btn_sessoes': 'Agenda de Sessões',
        'btn_cadastros': 'Cadastros',
        'tema_claro': 'Claro',
        'tema_escuro': 'Escuro',
        'tema_futurista': 'Futurista',
        'tema_vintage': 'Vintage',
        'titulo_dashboard': 'Painel de Indicadores & Gestão de Riscos',
        'total_alunos': 'Total de Alunos',
        'finalizados': 'Finalizados',
        'com_certificado': 'Com Certificado',
        'sem_certificado': 'Sem Certificado',
        'cursos_risco': 'Cursos em Risco',
        'painel_mentoria': 'Painel da Mentoria: Ritmo, Dedicação e Saúde do Progresso',
        'aluno': 'Aluno',
        'curso_materia': 'Curso / Matéria',
        'carga_horaria': 'Carga Horária',
        'progresso': 'Progresso',
        'prazo_meta': 'Prazo Meta',
        'status_saude': 'Status de Saúde',
        'sem_prazo': 'Sem prazo definido',
        'status_desativado': 'Desativado',
        'status_saudavel': 'Saudável / Em dia',
        'status_atencao': 'Em Atenção',
        'status_risco': 'Risco Crítico / Parado',
        'badge_saudaveis': 'Saudáveis',
        'badge_atencao': 'Em Atenção',
        'badge_risco': 'Em Risco',
        'nenhum_curso': 'Nenhum curso em andamento para análise de risco.',
        'catalogo_cursos': 'Catálogo de Cursos',
        'adicionar_novo_curso': '+ Adicionar Novo Curso',
        'nome_curso_material': 'Nome do Curso / Material',
        'plataforma': 'Plataforma',
        'tipo': 'Tipo',
        'carga_horaria_h': 'Carga Horária (h)',
        'status': 'Status',
        'link_url': 'Link (URL)',
        'exige_cert': 'Exige Cert.?',
        'salvar_novo_curso': 'Salvar Novo Curso',
        'cursos_disponiveis': 'Cursos Disponíveis na Plataforma',
        'col_id': 'ID',
        'col_nome_curso': 'Nome do Curso',
        'col_plataforma': 'Plataforma',
        'col_tipo': 'Tipo',
        'col_carga': 'Carga',
        'col_status': 'Status',
        'col_cadastrado_por': 'Cadastrado Por',
        'col_acoes': 'Ações',
        'btn_editar': 'Editar',
        'ativo': 'Ativo',
        'inativo': 'Inativo',
        'sim': 'Sim',
        'nao': 'Não',
        'sessoes_historico': 'Sessões e Histórico',
        'agendar_sessao': '+ Agendar Sessão',
        'col_data_hora': 'Data e Hora',
        'col_mentor': 'Mentor',
        'col_aluno': 'Aluno',
        'col_observacoes': 'Observações',
        'col_acoes_feedback': 'Ações / Feedback',
        'feedbacks': 'Feedbacks',
        'acompanhamento_estudos': 'Acompanhamento de Estudos',
        'vincular_aluno_curso': '+ Vincular Aluno a Curso',
        'perfil_entrevista': 'Perfil da Entrevista & Alinhamento',
        'rotulo_perfil': 'Perfil',
        'rotulo_objetivo': 'Objetivo Principal',
        'rotulo_expectativa': 'Expectativa',
        'nao_informado': 'Não informado',
        'nao_informada': 'Não informada',
        'progresso_pct': 'Progresso',
        'inicio': 'Início',
        'termino_meta': 'Término/Meta',
        'nao_definida': 'Não definida',
        'anotacoes_duvidas': 'Anotações / Dúvidas do Aluno:',
        'nenhuma_anotacao': 'Nenhuma anotação registrada.',
        'parecer_mentor': 'Parecer / Observações Importantes do Mentor:',
        'nenhum_parecer': 'Nenhum parecer do mentor registrado.',
        'atualizar_progresso_anotacoes': 'Atualizar Progresso & Anotações',
        'status_iniciado': 'Iniciado',
        'status_parado': 'Parado',
        'status_finalizado': 'Finalizado',
        'atualizar_acompanhamento_modal': 'Atualizar Acompanhamento',
        'edicao_perfil_entrevista': 'Edição do Perfil de Entrevista do Aluno',
        'data_inicio': 'Data de Início',
        'data_termino_meta': 'Data de Término (Meta)',
        'status_curso': 'Status do Curso',
        'progresso_porcentagem': 'Progresso (%)',
        'enviar_material_apoio': 'Enviar Material de Apoio',
        'cancelar': 'Cancelar',
        'salvar_alteracoes': 'Salvar Alterações',
        'gerenciamento_cadastros': 'Gerenciamento de Cadastros',
        'cadastrar_novo_usuario': '+ Cadastrar Novo Usuário',
        'nome': 'Nome',
        'email': 'E-mail',
        'nivel': 'Nível',
        'senha': 'Senha',
        'exigir_troca_senha': 'Exigir que este usuário troque a senha no próximo login',
        'salvar_cadastro': 'Salvar Cadastro',
        'usuarios_sistema': 'Usuários do Sistema e Auditoria',
        'data_criacao': 'Data de Criação',
        'criado_por': 'Criado por',
        'seguranca_senha': 'Segurança (Senha)',
        'acoes': 'Ações',
        'editar': 'Editar',
        'status_ausente': 'Ausente',
        'dados_acesso': 'Dados de Acesso',
        'nome_completo': 'Nome Completo',
        'nivel_acesso': 'Nível de Acesso',
        'nova_senha_opcional': 'Nova Senha (opcional)',
        'placeholder_senha': 'Deixe em branco para não alterar',
        'aviso_senha': 'Ao alterar a senha, a data de expiração será reiniciada.',
        'prontuario_entrevista': 'Prontuário de Entrevista e Alinhamento',
        'perfil_aluno': 'Perfil do Aluno',
        'observacoes_mentor_privativo': 'Observações / Parecer do Mentor (Privativo)',
        'nivel_aluno': 'Aluno',
        'nivel_mentor': 'Mentor',
        'nivel_mentor_admin': 'Mentor Administrador',
        'nivel_administrador': 'Administrador',
        'nome_app': 'Mentoria',
        'nivel_de_acesso': 'Nível de Acesso',
        'nova_sessao_mentoria': 'Nova Sessão de Mentoria',
        'selecionar_aluno': 'Selecionar Aluno',
        'escolha_um_aluno': 'Escolha um aluno...',
        'data_e_hora': 'Data e Hora',
        'pauta_observacoes': 'Pauta / Observações',
        'placeholder_pauta': 'Qual será o assunto desta mentoria?',
        'motivo_desativacao_label': 'Motivo da Desativação (Obrigatório se for desativar)',
        'motivo_desativacao_placeholder': 'Explique o motivo caso vá desativar o curso...',
        'vincular_aluno_curso_titulo': 'Vincular Aluno a um Curso',
        'selecionar_curso': 'Selecionar Curso',
        'escolha_um_curso': 'Escolha um curso...',
        'realizar_matricula': 'Realizar Matrícula',
        'historico_interacoes': 'Histórico de Interações (Registros imutáveis):',
        'escrever_comentario_avaliacao': 'Escrever Comentário / Avaliação:',
        'placeholder_feedback': 'Escreva aqui suas observações...',
        'enviar_feedback': 'Enviar Feedback',
        'publico_mentorado': 'Público (Para o Mentorado)',
        'tag_nota_interna': ' Nota Interna (Privado para Mentores)',
        'tag_publico_mentorado': ' Público (Para o Mentorado)',
        'titulo_grafico_evolucao': 'Linha do Tempo de Aprendizado',
        'titulo_grafico_skills': 'Equilíbrio de Habilidades',
        'placeholder_filtro': 'Filtrar por aluno ou nome do curso...',
        'ordenar_padrao': 'Ordenar por...',
        'ordem_curso_az': 'Curso (A-Z)',
        'ordem_curso_za': 'Curso (Z-A)',
        'ordem_carga_maior': 'Carga Horária (Maior - Menor)',
        'ordem_carga_menor': 'Carga Horária (Menor - Maior)',
        'ordem_progresso_maior': 'Progresso (Maior - Menor)',
        'ordem_progresso_menor': 'Progresso (Menor - Maior)',
        'label_volume_horas': 'Volume de Horas',
        'label_cursos_concluidos': 'Cursos Concluídos',
        'eixo_horas_estudadas': 'Horas Estudadas',
        'eixo_cursos_concluidos': 'Cursos Concluídos',
        'label_progresso_curso': 'Progresso no Curso (%)',
        'tipo_certificado': 'Certificação',
        'pendente': 'Pendente',
        'atribuir_mentores_cadastro': 'Atribuir Mentores (Apenas para Alunos)',
        'mentores_atribuidos': 'Mentores Atribuídos a este Aluno',
        'dica_selecao_multipla': 'Marque as caixas abaixo para selecionar um ou mais mentores.',
        'dica_selecao_multipla_edicao': 'Marque ou desmarque as caixas para alterar os mentores deste aluno.',
        'usuario': 'Usuário',
        'placeholder_perfil_aluno': 'Ex: Desenvolvedor Júnior, Analista de Sistemas...',
        'placeholder_objetivo': 'Qual o principal objetivo do aluno?',
        'placeholder_expectativa': 'Quais as expectativas do aluno?',
        'placeholder_observacoes_mentor': 'Anotações internas do mentor sobre o aluno...',
        'acessar_curso': 'Acessar Curso',
        'historico_feedback_titulo': 'Histórico de Feedback da Sessão',
        'nenhuma_sessao_encontrada': 'Nenhuma sessão de mentoria foi encontrada.',
        'manutencao_db': 'Manutenção (DB)',
        'manutencao_titulo': 'Manutenção do Banco de Dados',
        'manutencao_subtitulo': 'Gerencie a segurança e a integridade dos dados da plataforma.',
        'backup_imediato_titulo': 'Backup Imediato',
        'backup_imediato_desc': 'Baixa uma cópia instantânea do banco de dados para a sua máquina.',
        'btn_baixar_backup': '📁 Executar e Baixar Backup',
        'backup_agendado_titulo': 'Backup Agendado (Automático)',
        'backup_agendado_desc': 'Defina uma rotina para o sistema salvar o arquivo (mentory_MM-DD-AAAA_Hour.db).',
        'frequencia': 'Frequência',
        'freq_diario': 'Diário',
        'freq_semanal': 'Semanal',
        'freq_mensal': 'Mensal',
        'horario_execucao': 'Horário de Execução',
        'destino_interno': 'Destino Interno',
        'btn_salvar_rotina': '📅 Salvar Rotina',
        'restaurar_titulo': 'Restaurar Banco de Dados',
        'restaurar_desc': 'Atenção: Restaurar um backup substituirá TODOS os dados atuais pela versão do arquivo enviado.',
        'btn_restaurar': '⚠️ Restaurar Backup',
        'alerta_restaurar': 'ATENÇÃO: Você está prestes a sobrescrever o banco de dados. Essa ação não pode ser desfeita. Tem certeza?',
        'zona_perigo_titulo': 'Zona de Perigo: Limpar Banco de Dados',
        'zona_perigo_desc': 'Atenção Extrema: Esta ação destruirá TODOS os cursos, sessões, feedbacks, alunos e mentores cadastrados. Apenas a sua conta atual de Administrador sobreviverá. Um log permanente e inapagável será registrado no servidor para fins de auditoria.',
        'btn_apagar_tudo': '🗑️ Apagar Todos os Dados',
        'alerta_limpar': 'ALERTA CRÍTICO: Você tem certeza absoluta? Todos os dados serão destruídos permanentemente e a auditoria registrará sua ação. Esta operação não pode ser desfeita.',
        'btn_escolher_arquivo': 'Escolher Arquivo',
        'nenhum_arquivo': 'Nenhum arquivo escolhido',
        'solicitacoes': 'Solicitações',
        'solicitacoes_mentoria': 'Solicitações de Mentoria',
        'data_inicial': 'Data Inicial',
        'data_final': 'Data Final',
        'filtrar': 'Filtrar',
        'limpar_filtro': 'Limpar Filtro',
        'motivo': 'Motivo',
        'status_pendente': 'Pendente',
        'status_aprovado': 'Aprovado',
        'status_negado': 'Negado',
        'finalizado': 'Finalizado',
        'nenhuma_solicitacao_filtro': 'Nenhuma solicitação encontrada neste período.',
        'qa_interacoes': 'Q&A - Dúvidas e Interações com o Mentor',
        'em_data': 'em',
        'resposta_mentor': 'Resposta do Mentor:',
        'respondido_em': 'Respondido em:',
        'placeholder_obs_mentor': 'Insira as observações importantes do perfil identificado...',
        'escolher_arquivo': 'Escolher Arquivo',
        'nenhum_arquivo': 'Nenhum arquivo escolhido',
        'editar_usuario_titulo': 'Editar Usuário:',
        'historico_auditoria_titulo': 'Histórico e Auditoria de Backups',
        'data_inicial_filtro': 'Data Inicial',
        'data_final_filtro': 'Data Final',
        'btn_filtrar': 'Filtrar',
        'btn_limpar_filtro': 'Limpar',
        'col_data_registro': 'Data do Registro',
        'col_tipo': 'Tipo',
        'col_data_hora_alvo': 'Data/Hora Alvo',
        'col_status': 'Status',
        'col_usuario_autor': 'Usuário (Autor)',
        'col_destino_detalhes': 'Destino / Detalhes',
        'nenhum_registro_backup': 'Nenhum registro de backup encontrado no período.',
        'status_sucesso': 'Sucesso',
        'status_falha': 'Falha',
        'status_pendente': 'Pendente',
        'tipo_imediato': 'Imediato',
        'tipo_agendado': 'Agendado',
        'btn_agendar_estudo': '📅 Agendar Estudo Automático',
        'btn_conectar_agenda': '📅 Conectar Agenda',
        'btn_conectar_gemini': '🧠 Conectar Gemini Notebook',
        'modal_gemini_title': '🧠 Assistente Gemini Notebook',
        'modal_gemini_subtitle': 'Faça perguntas, peça resumos ou crie quizzes práticos baseados nas suas anotações.',
        'modal_gemini_welcome': '👋 Olá! Sou o seu assistente virtual. Posso ajudar você a criar simulados, revisar conceitos de arquitetura de nuvem, segurança ou analisar seus materiais. O que vamos estudar hoje?',
        'modal_gemini_placeholder': 'Ex: Crie 3 perguntas práticas de nível avançado sobre...',
        'btn_enviar': 'Enviar',
        'modal_gemini_loading': '⏳ Processando resposta...',
        'modal_gemini_error': 'Erro ao conectar com a IA.',
        'modal_materiais_titulo': '📄 Lista de Materiais de Apoio',
        'modal_materiais_subtitulo': 'Este curso possui múltiplos materiais. Escolha qual deseja acessar:',
        'tag_aluno': '👤 Aluno',
        'tag_mentor': '🎓 Mentor',
        'tag_antigo': '📎 Antigo',
        'btn_abrir': 'Abrir',
        'btn_material_unico': 'Material de Apoio',
        'btn_materiais_multiplos': 'Materiais de Apoio',
        'label_nova_pergunta': 'Fazer uma nova pergunta ao mentor:',
        'placeholder_nova_duvida': 'Digite sua dúvida sobre o estudo...',
        'placeholder_resposta_aluno': 'Digite a resposta para o aluno...',
        'msg_nenhuma_duvida': 'Nenhuma dúvida registrada neste estudo ainda.',
        'modal_parecer_titulo': 'Parecer Oficial do Mentor',
        'modal_parecer_ultima_atualizacao': 'Última atualização registrada:',
        'modal_parecer_instrucao_mentor': 'Escreva o parecer oficial, orientações gerais e avaliações sobre o desempenho do aluno neste estudo:',
        'modal_parecer_instrucao_aluno': 'Este é o parecer oficial e detalhado registrado pelo seu mentor para este curso:',
        'modal_parecer_placeholder': 'Insira o parecer oficial e detalhado aqui...',
        'modal_parecer_btn_salvar': 'Salvar Parecer Oficial',
        'modal_notas_titulo': 'Editor Expandido Anotações e Dúvidas',
        'modal_notas_instrucao': 'Escreva suas anotações, códigos, links ou dúvidas sobre este estudo com total liberdade e espaço:',
        'modal_notas_placeholder': 'Escreva suas anotações livremente aqui...',
        'modal_notas_btn_salvar': 'Salvar Anotações',
        'btn_expandir_tela_cheia': 'Expandir / Tela Cheia',
        'btn_expandir_parecer': 'Expandir Parecer',
        'badge_atualizado_em': 'Atualizado em:',
        'visibilidade_feedback': 'Visibilidade do Feedback',
        'opcao_publico': 'Público',
        'opcao_privado': 'Privado',
        'nav_cadastros': 'Cadastros',
        'nav_sino_novas_mensagens': 'Novas mensagens',
        'nav_sino_titulo': 'Notificações',
        'nav_sino_vazio': 'Nenhuma nova notificação',
        'tour_dash_intro': '<strong>Bem-vindo ao Painel Geral!</strong><br>Vamos fazer um tour rápido pelas principais ferramentas do seu perfil.',
        'tour_dash_topo': 'Aqui você visualiza seu nível de acesso atual e os atalhos rápidos de navegação.',
        'tour_dash_cartoes': 'Estes são os seus cartões de indicadores. Eles se adaptam se você for Aluno, Mentor ou Administrador.',
        'tour_dash_evolucao': '<strong>Linha do Tempo:</strong> Acompanhe o volume de horas estudadas ao longo do tempo.',
        'tour_dash_skills': '<strong>Equilíbrio de Habilidades:</strong> Mostra a distribuição do seu progresso.',
        'tour_dash_tabela': '<strong>Matriz de Acompanhamento:</strong> Visualize e gerencie os detalhes e status por aqui.',
        'tour_btn_proximo': 'Próximo',
        'tour_btn_anterior': 'Anterior',
        'tour_btn_concluir_sessoes': 'Ir para Sessões ➜',
        'tour_btn_cursos': 'Ir para Cursos ➜',
        'tour_cur_intro': '<strong>Catálogo de Cursos:</strong> Gerencie todos os treinamentos da plataforma por aqui.',
        'tour_cur_form': 'Preencha este formulário para cadastrar um novo curso, definindo plataforma e carga horária.',
        'tour_cur_tabela': 'Lista com todos os cursos ativos, permitindo edição rápida a qualquer momento.',
        'tour_ses_intro': '<strong>Sessões de Mentoria:</strong> Aqui você acompanha as reuniões e encontros.',
        'tour_ses_tabela': 'Tabela com data, pauta e botão de feedbacks para registrar avaliações.',
        'tour_aco_intro': '<strong>Bem-vindo ao Acompanhamento!</strong><br>Aqui é onde a magia dos estudos acontece.',
        'tour_aco_agenda': 'Conecte sua conta do Google para criar eventos direto na agenda.',
        'tour_aco_ia': 'Aqui você abre o Assistente Gemini IA para gerar quizzes e resumos!',
        'tour_aco_card': 'Neste painel, você acompanha o progresso e o status dos cursos.',
        'tour_cad_intro': '<strong>Gestão de Usuários:</strong> Central de controle de todos os membros do sistema.',
        'tour_cad_form': 'Use este formulário para registrar e aprovar novos Alunos, Mentores ou Administradores.',
        'tour_cad_tabela': 'Tabela completa para auditar acessos, forçar trocas de senhas e gerenciar perfis.',
        'tour_btn_sessoes': 'Ir para Sessões ➜',
        'tour_btn_acompanhamento': 'Avançar ➜',
        'tour_btn_cadastros': 'Avançar ➜',
        'tour_btn_voltar': 'Concluir ✅',
        'tour_btn_solicitacoes': 'Ir para Solicitações ➜',
        'tour_btn_manutencao': 'Ir para Manutenção ➜',
        'tour_sol_intro': '<strong>Painel de Solicitações:</strong> Aqui você gerencia os pedidos e requisições dos usuários.',
        'tour_sol_tabela': 'Acompanhe, aprove ou recuse rapidamente as solicitações pendentes.',
        'tour_man_intro': '<strong>Manutenção do Banco:</strong> Área restrita para gestão e segurança dos dados.',
        'tour_man_backup': 'Gere backups manuais ou restaure pontos de segurança do sistema.',
        'tour_man_auditoria': 'Histórico de auditoria para rastrear alterações. Lembre-se do nosso novo botão vermelho para limpar o log!',
        'tour_man_func1': '<strong>Backup do Sistema:</strong> Gere e faça o download seguro dos dados atuais.',
        'tour_man_func2': '<strong>Restauração:</strong> Importe um arquivo de backup para recuperar o sistema.',
        'tour_man_func3': '<strong>Limpeza de Logs:</strong> Otimize o banco apagando registros antigos e desnecessários.',
        'tour_man_func4': '<strong>Zona de Perigo:</strong> Ferramentas críticas (como reset de fábrica). Use com cautela!',
        'tour_man_filtro': 'Use este filtro de datas para encontrar eventos específicos na auditoria.',
        'tour_dash_filtros': '<strong>Painel da Mentoria:</strong> Use esta barra para filtrar alunos, buscar cursos específicos ou mudar a ordenação da tabela.',
        'tour_ses_agendar': '<strong>Agendar Sessão:</strong> Clique aqui para marcar um novo encontro ou reunião na plataforma.',
        'tour_aco_vincular': '<strong>Vincular Aluno:</strong> Atalho rápido para matricular um aluno em um novo curso diretamente por aqui.',
        'tour_man_apagar': '<strong>Zona de Perigo:</strong> Este é o botão para apagar permanentemente todo o histórico de auditoria visível.'
    },
    'en': {
        'painel_geral': 'Dashboard',
        'cursos': 'Courses',
        'sessoes': 'Sessions',
        'acompanhamento': 'Tracking',
        'cadastros': 'Registry',
        'sair': 'Sign Out',
        'conectado': 'Connected as',
        'tema': 'Theme',
        'idioma': 'Language',
        'btn_cursos': 'Courses',
        'btn_acompanhamento': 'My Tracking',
        'btn_sessoes': 'Session Schedule',
        'btn_cadastros': 'Registry',
        'tema_claro': 'Light',
        'tema_escuro': 'Dark',
        'tema_futurista': 'Futuristic',
        'tema_vintage': 'Vintage',
        'titulo_dashboard': 'Indicator Panel & Risk Management',
        'total_alunos': 'Total Students',
        'finalizados': 'Completed',
        'com_certificado': 'Certified',
        'sem_certificado': 'Uncertified',
        'cursos_risco': 'At-Risk Courses',
        'painel_mentoria': 'Mentorship Panel: Pace, Dedication and Progress Health',
        'aluno': 'Student',
        'curso_materia': 'Course / Subject',
        'carga_horaria': 'Duration',
        'progresso': 'Progress',
        'prazo_meta': 'Target Deadline',
        'status_saude': 'Health Status',
        'sem_prazo': 'No deadline set',
        'status_desativado': 'Disabled',
        'status_saudavel': 'Healthy / On track',
        'status_atencao': 'Attention Needed',
        'status_risco': 'Critical Risk / Stalled',
        'badge_saudaveis': 'Healthy',
        'badge_atencao': 'Attention',
        'badge_risco': 'At Risk',
        'nenhum_curso': 'No ongoing courses for risk analysis.',
        'catalogo_cursos': 'Course Catalog',
        'adicionar_novo_curso': '+ Add New Course',
        'nome_curso_material': 'Course Name / Material',
        'plataforma': 'Platform',
        'tipo': 'Type',
        'carga_horaria_h': 'Duration (h)',
        'status': 'Status',
        'link_url': 'Link (URL)',
        'exige_cert': 'Requires Cert.?',
        'salvar_novo_curso': 'Save New Course',
        'cursos_disponiveis': 'Available Courses on Platform',
        'col_id': 'ID',
        'col_nome_curso': 'Course Name',
        'col_plataforma': 'Platform',
        'col_tipo': 'Type',
        'col_carga': 'Duration',
        'col_status': 'Status',
        'col_cadastrado_por': 'Registered By',
        'col_acoes': 'Actions',
        'btn_editar': 'Edit',
        'ativo': 'Active',
        'inativo': 'Inactive',
        'sim': 'Yes',
        'nao': 'No',
        'sessoes_historico': 'Sessions and History',
        'agendar_sessao': '+ Schedule Session',
        'col_data_hora': 'Date and Time',
        'col_mentor': 'Mentor',
        'col_aluno': 'Student',
        'col_observacoes': 'Observations',
        'col_acoes_feedback': 'Actions / Feedback',
        'feedbacks': 'Feedbacks',
        'acompanhamento_estudos': 'Study Tracking',
        'vincular_aluno_curso': '+ Link Student to Course',
        'perfil_entrevista': 'Interview & Alignment Profile',
        'rotulo_perfil': 'Profile',
        'rotulo_objetivo': 'Main Objective',
        'rotulo_expectativa': 'Expectation',
        'nao_informado': 'Not informed',
        'nao_informada': 'Not informed',
        'progresso_pct': 'Progress',
        'inicio': 'Start',
        'termino_meta': 'Target Deadline',
        'nao_definida': 'Not defined',
        'anotacoes_duvidas': "Student's Notes / Questions:",
        'nenhuma_anotacao': 'No notes registered.',
        'parecer_mentor': "Mentor's Important Opinion / Observations:",
        'nenhum_parecer': 'No mentor opinion registered.',
        'atualizar_progresso_anotacoes': 'Update Progress & Notes',
        'status_iniciado': 'Started',
        'status_parado': 'Stalled',
        'status_finalizado': 'Completed',
        'atualizar_acompanhamento_modal': 'Update Tracking',
        'edicao_perfil_entrevista': "Edit Student's Interview Profile",
        'data_inicio': 'Start Date',
        'data_termino_meta': 'Target End Date',
        'status_curso': 'Course Status',
        'progresso_porcentagem': 'Progress (%)',
        'enviar_material_apoio': 'Upload Support Material',
        'cancelar': 'Cancel',
        'salvar_alteracoes': 'Save Changes',
        'gerenciamento_cadastros': 'User Management',
        'cadastrar_novo_usuario': '+ Register New User',
        'nome': 'Name',
        'email': 'E-mail',
        'nivel': 'Role',
        'senha': 'Password',
        'exigir_troca_senha': 'Require this user to change password on next login',
        'salvar_cadastro': 'Save Registration',
        'usuarios_sistema': 'System Users and Audit',
        'data_criacao': 'Creation Date',
        'criado_por': 'Created by',
        'seguranca_senha': 'Security (Password)',
        'acoes': 'Actions',
        'editar': 'Edit',
        'status_ausente': 'Away',
        'dados_acesso': 'Access Data',
        'nome_completo': 'Full Name',
        'nivel_acesso': 'Access Level',
        'nova_senha_opcional': 'New Password (optional)',
        'placeholder_senha': 'Leave blank to keep unchanged',
        'aviso_senha': 'Upon changing the password, the expiration date will reset.',
        'prontuario_entrevista': 'Interview and Alignment Record',
        'perfil_aluno': 'Student Profile',
        'observacoes_mentor_privativo': "Mentor's Notes / Opinion (Private)",
        'nivel_aluno': 'Student',
        'nivel_mentor': 'Mentor',
        'nivel_mentor_admin': 'Mentor Administrator',
        'nivel_administrador': 'Administrator',
        'nome_app': 'Mentorship',
        'nivel_de_acesso': 'Access Level',
        'nova_sessao_mentoria': 'New Mentorship Session',
        'selecionar_aluno': 'Select Student',
        'escolha_um_aluno': 'Choose a student...',
        'data_e_hora': 'Date and Time',
        'pauta_observacoes': 'Agenda / Observations',
        'placeholder_pauta': 'What will be the topic of this mentorship?',
        'motivo_desativacao_label': 'Deactivation Reason (Required if deactivating)',
        'motivo_desativacao_placeholder': 'Explain the reason if you are deactivating the course...',
        'vincular_aluno_curso_titulo': 'Link Student to a Course',
        'selecionar_curso': 'Select Course',
        'escolha_um_curso': 'Choose a course...',
        'realizar_matricula': 'Complete Enrollment',
        'historico_interacoes': 'Interaction History (Immutable records):',
        'escrever_comentario_avaliacao': 'Write Comment / Evaluation:',
        'placeholder_feedback': 'Write your observations here...',
        'enviar_feedback': 'Send Feedback',
        'publico_mentorado': 'Public (For the Mentees)',
        'tag_nota_interna': ' Internal Note (Private to Mentors)',
        'tag_publico_mentorado': ' Public (For the Mentees)',
        'titulo_grafico_evolucao': 'Learning Timeline',
        'titulo_grafico_skills': 'Skills Balance',
        'placeholder_filtro': 'Filter by student or course name...',
        'ordenar_padrao': 'Sort by...',
        'ordem_curso_az': 'Course (A-Z)',
        'ordem_curso_za': 'Course (Z-A)',
        'ordem_carga_maior': 'Workload (Highest - Lowest)',
        'ordem_carga_menor': 'Workload (Lowest - Highest)',
        'ordem_progresso_maior': 'Progress (Highest - Lowest)',
        'ordem_progresso_menor': 'Progress (Lowest - Highest)',
        'label_volume_horas': 'Volume of Hours',
        'label_cursos_concluidos': 'Completed Courses',
        'eixo_horas_estudadas': 'Hours Studied',
        'eixo_cursos_concluidos': 'Completed Courses',
        'label_progresso_curso': 'Course Progress (%)',
        'tipo_certificado': 'Certification',
        'pendente': 'Pending',
        'atribuir_mentores_cadastro': 'Assign Mentors (Students Only)',
        'mentores_atribuidos': 'Mentors Assigned to this Student',
        'dica_selecao_multipla': 'Check the boxes below to select one or more mentors.',
        'dica_selecao_multipla_edicao': 'Check or uncheck the boxes to manage the mentors for this student.',
        'usuario': 'User',
        'placeholder_perfil_aluno': 'E.g.: Junior Developer, Systems Analyst...',
        'placeholder_objetivo': "What is the student's main objective?",
        'placeholder_expectativa': "What are the student's expectations?",
        'placeholder_observacoes_mentor': "Mentor's internal notes about the student...",
        'acessar_curso': 'Access Course',
        'historico_feedback_titulo': 'Session Feedback History',
        'nenhuma_sessao_encontrada': 'No mentorship session found.',
        'manutencao_db': 'Maintenance (DB)',
        'manutencao_titulo': 'Database Maintenance',
        'manutencao_subtitulo': 'Manage the security and integrity of the platform data.',
        'backup_imediato_titulo': 'Immediate Backup',
        'backup_imediato_desc': 'Downloads an instant copy of the database to your machine.',
        'btn_baixar_backup': '📁 Execute and Download Backup',
        'backup_agendado_titulo': 'Scheduled Backup (Automatic)',
        'backup_agendado_desc': 'Define a routine for the system to save the file (mentory_MM-DD-AAAA_Hour.db).',
        'frequencia': 'Frequency',
        'freq_diario': 'Daily',
        'freq_semanal': 'Weekly',
        'freq_mensal': 'Monthly',
        'horario_execucao': 'Execution Time',
        'destino_interno': 'Internal Destination',
        'btn_salvar_rotina': '📅 Save Routine',
        'restaurar_titulo': 'Restore Database',
        'restaurar_desc': 'Warning: Restoring a backup will replace ALL current data with the uploaded file version.',
        'btn_restaurar': '⚠️ Restore Backup',
        'alerta_restaurar': 'WARNING: You are about to overwrite the database. This action cannot be undone. Are you sure?',
        'zona_perigo_titulo': 'Danger Zone: Clear Database',
        'zona_perigo_desc': 'Extreme Warning: This action will destroy ALL registered courses, sessions, feedbacks, students, and mentors. Only your current Administrator account will survive. A permanent and unerasable log will be recorded on the server for auditing purposes.',
        'btn_apagar_tudo': '🗑️ Delete All Data',
        'alerta_limpar': 'CRITICAL ALERT: Are you absolutely sure? All data will be permanently destroyed and auditing will record your action. This operation cannot be undone.',
        'btn_escolher_arquivo': 'Choose File',
        'nenhum_arquivo': 'No file chosen',
        'solicitacoes': 'Requests',
        'solicitacoes_mentoria': 'Mentorship Requests',
        'data_inicial': 'Start Date',
        'data_final': 'End Date',
        'filtrar': 'Filter',
        'limpar_filtro': 'Clear Filter',
        'motivo': 'Reason',
        'status_pendente': 'Pending',
        'status_aprovado': 'Approved',
        'status_negado': 'Denied',
        'finalizado': 'Finished',
        'nenhuma_solicitacao_filtro': 'No requests found in this period.',
        'qa_interacoes': 'Q&A - Doubts and Interactions with Mentor',
        'em_data': 'on',
        'resposta_mentor': 'Mentor\'s Answer:',
        'respondido_em': 'Answered on:',
        'placeholder_obs_mentor': 'Insert important observations about the identified profile...',
        'escolher_arquivo': 'Choose File',
        'nenhum_arquivo': 'No file chosen',
        'editar_usuario_titulo': 'Edit User:',
        'historico_auditoria_titulo': 'Backup History and Audit',
        'data_inicial_filtro': 'Start Date',
        'data_final_filtro': 'End Date',
        'btn_filtrar': 'Filter',
        'btn_limpar_filtro': 'Clear',
        'col_data_registro': 'Record Date',
        'col_tipo': 'Type',
        'col_data_hora_alvo': 'Target Date/Time',
        'col_status': 'Status',
        'col_usuario_autor': 'User (Author)',
        'col_destino_detalhes': 'Destination / Details',
        'nenhum_registro_backup': 'No backup records found in this period.',
        'status_sucesso': 'Success',
        'status_falha': 'Failed',
        'status_pendente': 'Pending',
        'tipo_imediato': 'Immediate',
        'tipo_agendado': 'Scheduled',
        'btn_agendar_estudo': '📅 Schedule Study',
        'btn_conectar_agenda': '📅 Connect Calendar',
        'btn_conectar_gemini': '🧠 Connect Gemini Notebook',
        'modal_gemini_title': '🧠 Gemini Notebook Assistant',
        'modal_gemini_subtitle': 'Ask questions, request summaries, or create practical quizzes based on your notes.',
        'modal_gemini_welcome': '👋 Hello! I am your virtual assistant. I can help you create simulations, review cloud architecture and security concepts, or analyze your materials. What are we studying today?',
        'modal_gemini_placeholder': 'Ex: Create 3 advanced practical questions about...',
        'btn_enviar': 'Send',
        'modal_gemini_loading': '⏳ Processing response...',
        'modal_gemini_error': 'Error connecting to the AI.',
        'modal_materiais_titulo': '📄 Support Materials List',
        'modal_materiais_subtitulo': 'This course has multiple materials. Choose which one to access:',
        'tag_aluno': '👤 Student',
        'tag_mentor': '🎓 Mentor',
        'tag_antigo': '📎 Old',
        'btn_abrir': 'Open',
        'btn_material_unico': 'Support Material',
        'btn_materiais_multiplos': 'Support Materials',
        'label_nova_pergunta': 'Ask the mentor a new question:',
        'placeholder_nova_duvida': 'Type your question about the study...',
        'placeholder_resposta_aluno': 'Type the response for the student...',
        'msg_nenhuma_duvida': 'No questions registered in this study yet.',
        'modal_parecer_titulo': 'Mentor\'s Official Opinion',
        'modal_parecer_ultima_atualizacao': 'Last update registered:',
        'modal_parecer_instrucao_mentor': 'Write the official opinion, general guidelines, and evaluations regarding the student\'s performance in this study:',
        'modal_parecer_instrucao_aluno': 'This is the official and detailed opinion registered by your mentor for this course:',
        'modal_parecer_placeholder': 'Insert the official and detailed opinion here...',
        'modal_parecer_btn_salvar': 'Save Official Opinion',
        'modal_notas_titulo': 'Expanded Notes and Doubts Editor',
        'modal_notas_instrucao': 'Write your notes, code, links, or questions about this study with total freedom and space:',
        'modal_notas_placeholder': 'Write your notes freely here...',
        'modal_notas_btn_salvar': 'Save Notes',
        'btn_expandir_tela_cheia': 'Expand / Full Screen',
        'btn_expandir_parecer': 'Expand Opinion',
        'badge_atualizado_em': 'Updated on:',
        'visibilidade_feedback': 'Feedback Visibility',
        'opcao_publico': 'Public',
        'opcao_privado': 'Private',
        'nav_cadastros': 'Registrations',
        'nav_sino_novas_mensagens': 'New messages',
        'nav_sino_titulo': 'Notifications',
        'nav_sino_vazio': 'No new notifications',
        'tour_dash_intro': '<strong>Welcome to the Dashboard!</strong><br>Let\'s take a quick tour of your profile\'s main tools.',
        'tour_dash_topo': 'Here you can view your current access level and quick navigation shortcuts.',
        'tour_dash_cartoes': 'These are your indicator cards. They adapt whether you are a Student, Mentor, or Administrator.',
        'tour_dash_evolucao': '<strong>Timeline:</strong> Track the volume of hours studied over time.',
        'tour_dash_skills': '<strong>Skills Balance:</strong> Shows the distribution of your progress.',
        'tour_dash_tabela': '<strong>Tracking Matrix:</strong> View and manage details and status here.',
        'tour_btn_proximo': 'Next',
        'tour_btn_anterior': 'Previous',
        'tour_btn_concluir_sessoes': 'Go to Sessions ➜',
        'tour_btn_cursos': 'Go to Courses ➜',
        'tour_cur_intro': '<strong>Course Catalog:</strong> Manage all platform training here.',
        'tour_cur_form': 'Fill out this form to register a new course, defining platform and workload.',
        'tour_cur_tabela': 'List of all active courses, allowing quick editing at any time.',
        'tour_ses_intro': '<strong>Mentoring Sessions:</strong> Track meetings and appointments here.',
        'tour_ses_tabela': 'Table with date, agenda, and feedback button to register evaluations.',
        'tour_aco_intro': '<strong>Welcome to Tracking!</strong><br>This is where the magic of studying happens.',
        'tour_aco_agenda': 'Connect your Google account to create events directly in your calendar.',
        'tour_aco_ia': 'Open the Gemini AI Assistant here to generate quizzes and summaries!',
        'tour_aco_card': 'On this panel, you track progress and course status.',
        'tour_cad_intro': '<strong>User Management:</strong> Control center for all system members.',
        'tour_cad_form': 'Use this form to register and approve new Students, Mentors, or Administrators.',
        'tour_cad_tabela': 'Complete table to audit access, force password changes, and manage profiles.',
        'tour_btn_sessoes': 'Go to Sessions ➜',
        'tour_btn_acompanhamento': 'Next ➜',
        'tour_btn_cadastros': 'Next ➜',
        'tour_btn_voltar': 'Done ✅',
        'tour_btn_solicitacoes': 'Go to Requests ➜',
        'tour_btn_manutencao': 'Go to Maintenance ➜',
        'tour_sol_intro': '<strong>Requests Panel:</strong> Here you manage user requests.',
        'tour_sol_tabela': 'Track, approve, or reject pending requests quickly.',
        'tour_man_intro': '<strong>DB Maintenance:</strong> Restricted area for data management and security.',
        'tour_man_backup': 'Generate manual backups or restore system security points.',
        'tour_man_auditoria': 'Audit history to track changes. Remember our new red button to clear the log!',
        'tour_man_func1': '<strong>System Backup:</strong> Generate and securely download current data.',
        'tour_man_func2': '<strong>Restore:</strong> Import a backup file to recover the system.',
        'tour_man_func3': '<strong>Log Cleanup:</strong> Optimize the database by deleting old records.',
        'tour_man_func4': '<strong>Danger Zone:</strong> Critical tools (like factory reset). Use with caution!',
        'tour_man_filtro': 'Use this date filter to find specific events in the audit.',
        'tour_dash_filtros': '<strong>Mentoring Panel:</strong> Use this bar to filter students, search for specific courses, or change table sorting.',
        'tour_ses_agendar': '<strong>Schedule Session:</strong> Click here to schedule a new meeting on the platform.',
        'tour_aco_vincular': '<strong>Link Student:</strong> Quick shortcut to enroll a student in a new course directly from here.',
        'tour_man_apagar': '<strong>Danger Zone:</strong> This is the button to permanently delete all visible audit history.'
        
    },
    'es': {
        'painel_geral': 'Panel General',
        'cursos': 'Cursos',
        'sessoes': 'Sesiones',
        'acompanhamento': 'Seguimiento',
        'cadastros': 'Registros',
        'sair': 'Cerrar Sesión',
        'conectado': 'Conectado como',
        'tema': 'Tema',
        'idioma': 'Idioma',
        'btn_cursos': 'Cursos',
        'btn_acompanhamento': 'Mi Seguimiento',
        'btn_sessoes': 'Agenda de Sesiones',
        'btn_cadastros': 'Registros',
        'tema_claro': 'Claro',
        'tema_escuro': 'Oscuro',
        'tema_futurista': 'Futurista',
        'tema_vintage': 'Vintage',
        'titulo_dashboard': 'Panel de Indicadores y Gestión de Riesgos',
        'total_alunos': 'Total de Estudiantes',
        'finalizados': 'Finalizados',
        'com_certificado': 'Con Certificado',
        'sem_certificado': 'Sin Certificado',
        'cursos_risco': 'Cursos en Riesgo',
        'painel_mentoria': 'Panel de Mentoría: Ritmo, Dedicación y Salud del Progreso',
        'aluno': 'Estudiante',
        'curso_materia': 'Curso / Materia',
        'carga_horaria': 'Duración',
        'progresso': 'Progreso',
        'prazo_meta': 'Plazo Meta',
        'status_saude': 'Estado de Salud',
        'sem_prazo': 'Sin plazo definido',
        'status_desativado': 'Desactivado',
        'status_saudavel': 'Saludable / Al día',
        'status_atencao': 'En Atención',
        'status_risco': 'Riesgo Crítico / Detenido',
        'badge_saudaveis': 'Saludables',
        'badge_atencao': 'En Atención',
        'badge_risco': 'En Riesgo',
        'nenhum_curso': 'Ningún curso en curso para análisis de riesgo.',
        'catalogo_cursos': 'Catálogo de Cursos',
        'adicionar_novo_curso': '+ Agregar Nuevo Curso',
        'nome_curso_material': 'Nombre del Curso / Material',
        'plataforma': 'Plataforma',
        'tipo': 'Tipo',
        'carga_horaria_h': 'Duración (h)',
        'status': 'Estado',
        'link_url': 'Enlace (URL)',
        'exige_cert': 'Exige Cert.?',
        'salvar_novo_curso': 'Guardar Nuevo Curso',
        'cursos_disponiveis': 'Cursos Disponibles en la Plataforma',
        'col_id': 'ID',
        'col_nome_curso': 'Nombre del Curso',
        'col_plataforma': 'Plataforma',
        'col_tipo': 'Tipo',
        'col_carga': 'Duración',
        'col_status': 'Estado',
        'col_cadastrado_por': 'Registrado Por',
        'col_acoes': 'Acciones',
        'btn_editar': 'Editar',
        'ativo': 'Activo',
        'inativo': 'Inactivo',
        'sim': 'Sí',
        'nao': 'No',
        'sessoes_historico': 'Sesiones e Historial',
        'agendar_sessao': '+ Programar Sesión',
        'col_data_hora': 'Fecha y Hora',
        'col_mentor': 'Mentor',
        'col_aluno': 'Estudiante',
        'col_observacoes': 'Observaciones',
        'col_acoes_feedback': 'Acciones / Comentarios',
        'feedbacks': 'Comentarios',
        'acompanhamento_estudos': 'Seguimiento de Estudios',
        'vincular_aluno_curso': '+ Vincular Estudiante a Curso',
        'perfil_entrevista': 'Perfil de Entrevista y Alineación',
        'rotulo_perfil': 'Perfil',
        'rotulo_objetivo': 'Objetivo Principal',
        'rotulo_expectativa': 'Expectativa',
        'nao_informado': 'No informado',
        'nao_informada': 'No informada',
        'progresso_pct': 'Progreso',
        'inicio': 'Inicio',
        'termino_meta': 'Plazo Meta',
        'nao_definida': 'No definida',
        'anotacoes_duvidas': 'Notas / Dudas del Estudiante:',
        'nenhuma_anotacao': 'Ninguna nota registrada.',
        'parecer_mentor': 'Dictamen / Observaciones Importantes del Mentor:',
        'nenhum_parecer': 'Ningún dictamen del mentor registrado.',
        'atualizar_progresso_anotacoes': 'Actualizar Progreso y Notas',
        'status_iniciado': 'Iniciado',
        'status_parado': 'Detenido',
        'status_finalizado': 'Finalizado',
        'atualizar_acompanhamento_modal': 'Actualizar Seguimiento',
        'edicao_perfil_entrevista': 'Edición del Perfil de Entrevista del Estudiante',
        'data_inicio': 'Fecha de Inicio',
        'data_termino_meta': 'Fecha de Finalización (Meta)',
        'status_curso': 'Estado del Curso',
        'progresso_porcentagem': 'Progreso (%)',
        'enviar_material_apoio': 'Enviar Material de Apoyo',
        'cancelar': 'Cancelar',
        'salvar_alteracoes': 'Guardar Cambios',
        'gerenciamento_cadastros': 'Gestión de Usuarios',
        'cadastrar_novo_usuario': '+ Registrar Nuevo Usuario',
        'nome': 'Nombre',
        'email': 'Correo electrónico',
        'nivel': 'Rol',
        'senha': 'Contraseña',
        'exigir_troca_senha': 'Exigir que este usuario cambie su contraseña en el próximo inicio de sesión',
        'salvar_cadastro': 'Guardar Registro',
        'usuarios_sistema': 'Usuarios del Sistema y Auditoría',
        'data_criacao': 'Fecha de Creación',
        'criado_por': 'Creado por',
        'seguranca_senha': 'Seguridad (Contraseña)',
        'acoes': 'Acciones',
        'editar': 'Editar',
        'status_ausente': 'Ausente',
        'dados_acesso': 'Datos de Acceso',
        'nome_completo': 'Nombre Completo',
        'nivel_acesso': 'Nivel de Acceso',
        'nova_senha_opcional': 'Nueva Contraseña (opcional)',
        'placeholder_senha': 'Dejar en blanco para no modificar',
        'aviso_senha': 'Al cambiar la contraseña, la fecha de expiración se reiniciará.',
        'prontuario_entrevista': 'Expediente de Entrevista y Alineación',
        'perfil_aluno': 'Perfil del Estudiante',
        'observacoes_mentor_privativo': 'Observaciones / Dictamen del Mentor (Privado)',
        'nivel_aluno': 'Estudiante',
        'nivel_mentor': 'Mentor',
        'nivel_mentor_admin': 'Mentor Administrador',
        'nivel_administrador': 'Administrador',
        'nome_app': 'Mentoría',
        'nivel_de_acesso': 'Nivel de Acceso',
        'nova_sessao_mentoria': 'Nueva Sesión de Mentoría',
        'selecionar_aluno': 'Seleccionar Estudiante',
        'escolha_um_aluno': 'Elija un estudiante...',
        'data_e_hora': 'Fecha y Hora',
        'pauta_observacoes': 'Agenda / Observaciones',
        'placeholder_pauta': '¿Cuál será el tema de esta mentoría?',
        'motivo_desativacao_label': 'Motivo de Desactivación (Obligatorio si va a desactivar)',
        'motivo_desativacao_placeholder': 'Explique el motivo en caso de desactivar el curso...',
        'vincular_aluno_curso_titulo': 'Vincular Estudiante a un Curso',
        'selecionar_curso': 'Seleccionar Curso',
        'escolha_um_curso': 'Elija un curso...',
        'realizar_matricula': 'Realizar Matrícula',
        'historico_interacoes': 'Historial de Interacciones (Registros inmutables):',
        'escrever_comentario_avaliacao': 'Escribir Comentario / Evaluación:',
        'placeholder_feedback': 'Escriba aquí sus observaciones...',
        'enviar_feedback': 'Enviar Comentario',
        'publico_mentorado': 'Público (Para el Mentorado)',
        'tag_nota_interna': ' Nota Interna (Privado para Mentores)',
        'tag_publico_mentorado': ' Público (Para el Mentorado)',
        'titulo_grafico_evolucao': 'Línea de Tiempo de Aprendizaje',
        'titulo_grafico_skills': 'Equilibrio de Habilidades',
        'placeholder_filtro': 'Filtrar por estudiante o nombre del curso...',
        'ordenar_padrao': 'Ordenar por...',
        'ordem_curso_az': 'Curso (A-Z)',
        'ordem_curso_za': 'Curso (Z-A)',
        'ordem_carga_maior': 'Carga Horaria (Mayor - Menor)',
        'ordem_carga_menor': 'Carga Horaria (Menor - Mayor)',
        'ordem_progresso_maior': 'Progreso (Mayor - Menor)',
        'ordem_progresso_menor': 'Progreso (Menor - Mayor)',
        'label_volume_horas': 'Volumen de Horas',
        'label_cursos_concluidos': 'Cursos Completados',
        'eixo_horas_estudadas': 'Horas Estudiadas',
        'eixo_cursos_concluidos': 'Cursos Completados',
        'label_progresso_curso': 'Progreso del Curso (%)',
        'tipo_certificado': 'Certificación',
        'pendente': 'Pendiente',
        'atribuir_mentores_cadastro': 'Asignar Mentores (Solo para Estudiantes)',
        'mentores_atribuidos': 'Mentores Asignados a este Estudiante',
        'dica_selecao_multipla': 'Marque las casillas a continuación para seleccionar uno o más mentores.',
        'dica_selecao_multipla_edicao': 'Marque o desmarque las casillas para modificar los mentores de este estudiante.',
        'usuario': 'Usuario',
        'placeholder_perfil_aluno': 'Ej: Desarrollador Junior, Analista de Sistemas...',
        'placeholder_objetivo': '¿Cuál es el objetivo principal del estudiante?',
        'placeholder_expectativa': '¿Cuáles son las expectativas del estudiante?',
        'placeholder_observacoes_mentor': 'Anotaciones internas del mentor sobre el estudiante...',
        'acessar_curso': 'Acceder al Curso',
        'historico_feedback_titulo': 'Historial de Feedback de la Sesión',
        'nenhuma_sessao_encontrada': 'No se encontró ninguna sesión de mentoría.',
        'manutencao_db': 'Mantenimiento (DB)',
        'manutencao_titulo': 'Mantenimiento de la Base de Datos',
        'manutencao_subtitulo': 'Administre la seguridad e integridad de los datos de la plataforma.',
        'backup_imediato_titulo': 'Copia de Seguridad Inmediata',
        'backup_imediato_desc': 'Descarga una copia instantánea de la base de datos a su máquina.',
        'btn_baixar_backup': '📁 Ejecutar y Descargar Copia',
        'backup_agendado_titulo': 'Copia de Seguridad Programada (Automática)',
        'backup_agendado_desc': 'Defina una rutina para que el sistema guarde el archivo (mentory_MM-DD-AAAA_Hour.db).',
        'frequencia': 'Frecuencia',
        'freq_diario': 'Diario',
        'freq_semanal': 'Semanal',
        'freq_mensal': 'Mensual',
        'horario_execucao': 'Hora de Ejecución',
        'destino_interno': 'Destino Interno',
        'btn_salvar_rotina': '📅 Guardar Rutina',
        'restaurar_titulo': 'Restaurar Base de Datos',
        'restaurar_desc': 'Atención: Restaurar una copia reemplazará TODOS los datos actuales por la versión del archivo enviado.',
        'btn_restaurar': '⚠️ Restaurar Copia',
        'alerta_restaurar': 'ATENCIÓN: Está a punto de sobrescribir la base de datos. Esta acción no se puede deshacer. ¿Está seguro?',
        'zona_perigo_titulo': 'Zona de Peligro: Limpiar Base de Datos',
        'zona_perigo_desc': 'Advertencia Extrema: Esta acción destruirá TODOS los cursos, sesiones, comentarios, estudiantes y mentores registrados. Solo sobrevivirá su cuenta de Administrador actual. Se registrará un registro permanente e imborrable en el servidor para fines de auditoría.',
        'btn_apagar_tudo': '🗑️ Borrar Todos los Datos',
        'alerta_limpar': 'ALERTA CRÍTICA: ¿Está absolutamente seguro? Todos los datos serán destruidos permanentemente y la auditoría registrará su acción. Esta operación no se puede deshacer.',
        'btn_escolher_arquivo': 'Elegir Archivo',
        'nenhum_arquivo': 'Ningún archivo seleccionado',
        'solicitacoes': 'Solicitudes',
        'solicitacoes_mentoria': 'Solicitudes de Mentoría',
        'data_inicial': 'Fecha Inicial',
        'data_final': 'Fecha Final',
        'filtrar': 'Filtrar',
        'limpar_filtro': 'Limpiar Filtro',
        'motivo': 'Motivo',
        'status_pendente': 'Pendiente',
        'status_aprovado': 'Aprobado',
        'status_negado': 'Rechazado',
        'finalizado': 'Finalizado',
        'nenhuma_solicitacao_filtro': 'No se encontraron solicitudes en este período.',
        'qa_interacoes': 'Q&A - Dudas e Interacciones con el Mentor',
        'em_data': 'el',
        'resposta_mentor': 'Respuesta del Mentor:',
        'respondido_em': 'Respondido el:',
        'placeholder_obs_mentor': 'Inserte observaciones importantes sobre el perfil identificado...',
        'escolher_arquivo': 'Elegir Archivo',
        'nenhum_arquivo': 'Ningún archivo seleccionado',
        'editar_usuario_titulo': 'Edit User:',
        'historico_auditoria_titulo': 'Historial y Auditoría de Backups',
        'data_inicial_filtro': 'Fecha Inicial',
        'data_final_filtro': 'Fecha Final',
        'btn_filtrar': 'Filtrar',
        'btn_limpar_filtro': 'Limpiar',
        'col_data_registro': 'Fecha de Registro',
        'col_tipo': 'Tipo',
        'col_data_hora_alvo': 'Fecha/Hora Objetivo',
        'col_status': 'Estado',
        'col_usuario_autor': 'Usuario (Autor)',
        'col_destino_detalhes': 'Destino / Detalles',
        'nenhum_registro_backup': 'No se encontraron registros de backup en el período.',
        'status_sucesso': 'Éxito',
        'status_falha': 'Fallo',
        'status_pendente': 'Pendiente',
        'tipo_imediato': 'Inmediato',
        'tipo_agendado': 'Programado',
        # Cole as novas aqui, garantindo que tenham vírgula no final da linha anterior:
        'btn_agendar_estudo': '📅 Programar Estudio Automático',
        'btn_conectar_agenda': '📅 Conectar Calendario',
        'btn_conectar_gemini': '🧠 Conectar Gemini Notebook',
        'modal_gemini_title': '🧠 Asistente Gemini Notebook',
        'modal_gemini_subtitle': 'Haz preguntas, pide resúmenes o crea cuestionarios prácticos basados en tus apuntes.',
        'modal_gemini_welcome': '👋 ¡Hola! Soy tu asistente virtual. Puedo ayudarte a crear simulacros, revisar conceptos de arquitectura en la nube, seguridad o analizar tus materiales. ¿Qué vamos a estudiar hoy?',
        'modal_gemini_placeholder': 'Ej: Crea 3 preguntas prácticas de nivel avanzado sobre...',
        'btn_enviar': 'Enviar',
        'modal_gemini_loading': '⏳ Procesando respuesta...',
        'modal_gemini_error': 'Error al conectar con la IA.',
        'modal_materiais_titulo': '📄 Lista de Materiales de Apoyo',
        'modal_materiais_subtitulo': 'Este curso tiene múltiples materiales. Elige cuál deseas acceder:',
        'tag_aluno': '👤 Alumno',
        'tag_mentor': '🎓 Mentor',
        'tag_antigo': '📎 Antiguo',
        'btn_abrir': 'Abrir',
        'btn_material_unico': 'Material de Apoyo',
        'btn_materiais_multiplos': 'Materiales de Apoyo',
        'label_nova_pergunta': 'Hacer una nueva pregunta al mentor:',
        'placeholder_nova_duvida': 'Escribe tu duda sobre el estudio...',
        'placeholder_resposta_aluno': 'Escribe la respuesta para el alumno...',
        'msg_nenhuma_duvida': 'Aún no hay dudas registradas en este estudio.',
        'modal_parecer_titulo': 'Dictamen Oficial del Mentor',
        'modal_parecer_ultima_atualizacao': 'Última actualización registrada:',
        'modal_parecer_instrucao_mentor': 'Escriba el dictamen oficial, orientaciones generales y evaluaciones sobre el desempeño del alumno en este estudio:',
        'modal_parecer_instrucao_aluno': 'Este es el dictamen oficial y detallado registrado por su mentor para este curso:',
        'modal_parecer_placeholder': 'Inserte el dictamen oficial y detallado aquí...',
        'modal_parecer_btn_salvar': 'Guardar Dictamen Oficial',
        'modal_notas_titulo': 'Editor Expandido de Notas y Dudas',
        'modal_notas_instrucao': 'Escribe tus notas, códigos, enlaces o dudas sobre este estudio con total libertad y espacio:',
        'modal_notas_placeholder': 'Escribe tus notas libremente aquí...',
        'modal_notas_btn_salvar': 'Guardar Notas',
        'btn_expandir_tela_cheia': 'Expandir / Pantalla Completa',
        'btn_expandir_parecer': 'Expandir Dictamen',
        'badge_atualizado_em': 'Actualizado el:',
        'visibilidade_feedback': 'Visibilidad de los Comentarios',
        'opcao_publico': 'Público',
        'opcao_privado': 'Privado',
        'nav_cadastros': 'Registros',
        'nav_sino_novas_mensagens': 'Nuevos mensajes',
        'nav_sino_titulo': 'Notificaciones',
        'nav_sino_vazio': 'Ninguna notificación nueva',
        'tour_dash_intro': '<strong>¡Bienvenido al Panel General!</strong><br>Hagamos un recorrido rápido por las herramientas principales de su perfil.',
        'tour_dash_topo': 'Aquí puede ver su nivel de acceso actual y los atajos de navegación rápidos.',
        'tour_dash_cartoes': 'Estas son sus tarjetas de indicadores. Se adaptan si es Alumno, Mentor o Administrador.',
        'tour_dash_evolucao': '<strong>Línea de Tiempo:</strong> Siga el volumen de horas estudiadas a lo largo del tiempo.',
        'tour_dash_skills': '<strong>Equilibrio de Habilidades:</strong> Muestra la distribución de su progreso.',
        'tour_dash_tabela': '<strong>Matriz de Seguimiento:</strong> Vea y administre los detalles y el estado aquí.',
        'tour_btn_proximo': 'Siguiente',
        'tour_btn_anterior': 'Anterior',
        'tour_btn_concluir_sessoes': 'Ir a Sesiones ➜',
        'tour_btn_cursos': 'Ir a Cursos ➜',
        'tour_cur_intro': '<strong>Catálogo de Cursos:</strong> Gestione todos los entrenamientos de la plataforma aquí.',
        'tour_cur_form': 'Complete este formulario para registrar un nuevo curso, definiendo plataforma y carga horaria.',
        'tour_cur_tabela': 'Lista de todos los cursos activos, permitiendo edición rápida en cualquier momento.',
        'tour_ses_intro': '<strong>Sesiones de Mentoría:</strong> Aquí realiza el seguimiento de reuniones y encuentros.',
        'tour_ses_tabela': 'Tabla con fecha, agenda y botón de feedback para registrar evaluaciones.',
        'tour_aco_intro': '<strong>¡Bienvenido al Seguimiento!</strong><br>Aquí es donde ocurre la magia de los estudios.',
        'tour_aco_agenda': 'Conecte su cuenta de Google para crear eventos directamente en la agenda.',
        'tour_aco_ia': '¡Abra el Asistente Gemini AI aquí para generar cuestionarios y resúmenes!',
        'tour_aco_card': 'En este panel, realiza el seguimiento del progreso y estado de los cursos.',
        'tour_cad_intro': '<strong>Gestión de Usuarios:</strong> Centro de control para todos los miembros del sistema.',
        'tour_cad_form': 'Use este formulario para registrar y aprobar nuevos Alumnos, Mentores o Administradores.',
        'tour_cad_tabela': 'Tabla completa para auditar accesos, forzar cambios de contraseña y gestionar perfiles.',
        'tour_btn_sessoes': 'Ir a Sesiones ➜',
        'tour_btn_acompanhamento': 'Avanzar ➜',
        'tour_btn_cadastros': 'Avanzar ➜',
        'tour_btn_voltar': 'Listo ✅',
        'tour_btn_solicitacoes': 'Ir a Solicitudes ➜',
        'tour_btn_manutencao': 'Ir a Mantenimiento ➜',
        'tour_sol_intro': '<strong>Panel de Solicitudes:</strong> Aquí gestiona los pedidos de los usuarios.',
        'tour_sol_tabela': 'Rastree, apruebe o rechace rápidamente las solicitudes pendientes.',
        'tour_man_intro': '<strong>Mantenimiento de BD:</strong> Área restringida para gestión y seguridad de datos.',
        'tour_man_backup': 'Genere copias de seguridad manuales o restaure puntos de seguridad del sistema.',
        'tour_man_auditoria': 'Historial de auditoría para rastrear cambios. ¡Recuerde nuestro nuevo botón rojo para limpiar el registro!',
        'tour_man_func1': '<strong>Copia de Seguridad:</strong> Genere y descargue de forma segura los datos actuales.',
        'tour_man_func2': '<strong>Restauración:</strong> Importe un archivo de respaldo para recuperar el sistema.',
        'tour_man_func3': '<strong>Limpieza de Registros:</strong> Optimice la base de datos eliminando registros antiguos.',
        'tour_man_func4': '<strong>Zona de Peligro:</strong> Herramientas críticas (como el restablecimiento de fábrica). ¡Úselo con precaución!',
        'tour_man_filtro': 'Use este filtro de fechas para encontrar eventos específicos en la auditoría.',
        'tour_dash_filtros': '<strong>Panel de Mentoría:</strong> Use esta barra para filtrar alumnos, buscar cursos específicos o cambiar la clasificación de la tabla.',
        'tour_ses_agendar': '<strong>Programar Sesión:</strong> Haga clic aquí para programar una nueva reunión en la plataforma.',
        'tour_aco_vincular': '<strong>Vincular Alumno:</strong> Atajo rápido para inscribir a un alumno en un nuevo curso directamente desde aquí.',
        'tour_man_apagar': '<strong>Zona de Peligro:</strong> Este es el botón para eliminar permanentemente todo el historial de auditoría visible.'
        
    }
}

def t(chave, idioma='pt'):
    """Retorna a tradução com base na chave e no idioma escolhido."""
    if idioma not in TEXTOS:
        idioma = 'pt'
    return TEXTOS[idioma].get(chave, TEXTOS['pt'].get(chave, chave))